# Generated by Django 2.0.4 on 2018-04-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180411_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hex',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
