# Generated by Django 2.0.4 on 2018-04-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180421_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
    ]
