# Generated by Django 2.0.4 on 2018-05-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20180509_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='accessories',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='designer_dress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='wedding_collection',
            field=models.BooleanField(default=False),
        ),
    ]
